Neuer blogeintrag 33
dxiai/dxiai.github.io pull request #37
Opened 2021-05-25 14:27 UTC by memetnur

der erste Beitrag zum Blog "MacOS für Life Sciences Studierende startklar machen" ist fertig erstellt.  Bitte @phish108 durchlesen und mir ein Feedback zum Blogeintrag geben.

Vielen Dank
Nuri

2021-05-25 21:43 UTC, phish108 requested changes
Ich habe zusätzlich zu meinen Änderungsvorschlägen weitere Anmerkungen gemacht. Pass auf, dass du sie nicht übersiehst. 

Ich fände es auch gut, wenn du die Software mit Links versehen würdest, so weiss jede(r) gleich Bescheid, woher man die Apps bekommt. 

Ich habe auch hier und dort Anmerkungen gemacht, wenn eine App gut über Homebrew installiert werden kann.

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +- **OmniGraffle**: ist eine Möglichkeit die Organisation und Aufbereitung von Daten in übersichtliche Diagramme, Charts und Mindmaps zu illustrieren.
```suggestion
- **OmniGraffle**: Ist eine App, um übersichtliche Diagramme, Charts und Mindmaps zu erstellen. Sie ist super leistungsfähig aber leider auch recht teuer. 
```

Ich würde OmniGraffle rausnehmen. Ich habe mir Draw.io genauer angesehen und es ist inzwischen eine super und vor Allem kostenlose Alternative zu OmniGraffle.

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +
```suggestion

Weil manche Lehrveranstaltungen Zoom und manche WebEx verwenden, sollten unbedingt beide Apps auf dem Laptop installiert sein. 
```

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +- **Toggl Track**: ist eine Zeiterfassungssoftware und verfolgt Zeitblöcke, die optional mit einer Aufgabe, einem Projekt und Tags gekennzeichnet sind.
```suggestion
- **Toggl Track**: Ist eine Zeiterfassungssoftware und verfolgt Zeitblöcke, die optional mit einer Aufgabe, einem Projekt und Tags gekennzeichnet sind. So behältst du deine Studienzeit im Blick. 
```

Toogl hat nichts mit Informatik zu tun. Ich würde das nach oben zu Office dazu tun.

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +-**Git / GitHub**: ist ein freies verteiltes Versionskontrollsystem, um deine Arbeiten schnell und effizient zu bearbeiten.
Wichtig: In Markdown musst du einen Leerschlag nach dem Minus machen, damit du eine Liste erzeugst.

Nach einem Doppelpunkt schreibt man gross weiter ;)

```suggestion
- **Git / GitHub**: Ist ein freies verteiltes Versionskontrollsystem, um deine Arbeiten schnell und effizient zu sichern.
```

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +-**Matlab**: ist eine Plattform für Programmierung und numerische Berechnungen zur Analyse von Daten, Entwicklung von Algorithmen und Erstellung von Modellen.
```suggestion
- **MathLab**: Ist eine Plattform für Programmierung und numerische Berechnungen zur Analyse von Daten, Entwicklung von Algorithmen und Erstellung von Modellen. MathLab wird vor Allem in BioTechnologie und Chemie eingesetzt.
```

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +-**R und RStudio**: ist eine Softwareumgebung für statistische Berechnungen und Grafiken.
```suggestion
- **R und RStudio**: Ist eine Softwareumgebung für statistische Berechnungen und Datenvisualisierungen. R und RStudio sind recht umständlich zu installieren. Am Besten installiert man beide Tools über Homebrew: 

  - [R](https://formulae.brew.sh/cask/r)
  - [RStudio](https://formulae.brew.sh/cask/rstudio)
```

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +- **Xcode**: ist eine Entwicklungsumgebung um Programme für MacOs Benutzer zu entwicklen.
```suggestion
- **Xcode**: Ist die Entwicklungsumgebung, um Programme für MacOS selbst zu entwicklen oder um Apps mit **Homebrew** zu installieren. Xcode braucht zwar extrem viel Platz, sollte aber auf keinem MacBook fehlen.
```

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +Die [Studyhouse](https://www.studyhouse.ch/cgi-bin/home)können Software-Lizenzen für Studierende zu Sonderpreisen bezogen werden.
```suggestion
Über [Studyhouse](https://www.studyhouse.ch/cgi-bin/home) können Software-Lizenzen für Studierende zu Sonderpreisen bezogen werden. Bevor du das machst, prüfe unbedingt, ob du diese Lizenz nicht von der ZHAW umsonst zur Verfügung gestellt bekommst. 
```

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +Chacon, S., & Long, J. (2021). Git. https://git-scm.com/
```suggestion
- Chacon, S., & Long, J. (2021). Git. https://git-scm.com/
```

Mach unbedingt eine Liste aus deinen Referenzen.

2021-05-25 21:43 UTC, phish108 commented on _posts/2021-06-05-memn
> +### Literaturverzeichnis
Verwende lieber Referenzen als Literaturverzeichnis. Das Meiste ist nämlich keine Literatur. Ich empfehle dir das auch in deinen anderen Dokumenten so beizubehalten.


```suggestion
### Referenzen
```

2021-06-01 13:46 UTC, memetnur reviewed
diverse Änderungen von @phish108 wurden übernommen. hierbei danke!

2021-06-01 13:47 UTC, merged